### PR TITLE
StarSettings: Set --outFilterScoreMin=20

### PR DESCRIPTION
**Pull request by sjackman**
Filter out alignment artifacts of reagent sequences.

See https://10xtech.atlassian.net/browse/CELLRANGER-3434
and https://github.com/10XDev/cellranger/pull/3390

### CODE REVIEW

**Comment by nlhepler** [comment]
Is there a JIRA for this issue? It would be good to have an understanding of the background.

Also, this is fairly high-blast-radius change for something that could be narrowly tailored to specifically reagent sequences. Have you done some plygo A/B testing to see what impact, if any, this has?

**Comment by sjackman** [comment]
> Is there a JIRA for this issue? It would be good to have an understanding of the background.

The JIRA issue is https://10xtech.atlassian.net/browse/CELLRANGER-3434

> Also, this is fairly high-blast-radius change for something that could be narrowly tailored to specifically reagent sequences. Have you done some plygo A/B testing to see what impact, if any, this has?

STAR's default parameter `--outFilterScoreMinOverLread=0.66`, when all the reads were equal length without trimming, is equivalent to `--outFilterScoreMin=(0.66 * r2_length)`, so we've effectively already been using `--outFilterScoreMin`.

After trimming, we discovered that very short alignments of say 11 bp of a 16 bp read after trimming can make it through, and believe it or not, be uniquely mapped to a gene in the transcriptome.

> EDIT: P.S. it would be good to fix the failing test.

On it!

**Comment by sreenathkrishnan** [comment]
Wouldn't `--outFilterMatchNmin=20` be preferred as you mentioned in the JIRA over `--outFilterScoreMin=20`?

**Comment by sjackman** [comment]
Wouldn't `--outFilterMatchNmin=20` be preferred as you mentioned in the JIRA over `--outFilterScoreMin=20`?

My intuition is that alignment score is preferable. If for example you have a 26 bp read with 20 matches and 6 mismatches, and an alignment score of 14, that read should probably _not_ be output. I'd also prefer the filter that gives more transparency by filtering on the score that's more readily available in the BAM file. Alignment score `AS:i` is readily available, but number of matches is not; it needs to be computed from the sum of the match `M` ops in the CIGAR and number of mismatches `NM:i`.

**Comment by nlhepler** [comment]
Could you draft a PR for cellranger using this orbit commit and run the dev tests and a small sample of single-ended and paired-ended (3-5 total) tests and compare their metrics? Presumably they should be mostly unchanged. If so, :+1:

**Comment by sjackman** [comment]
> Could you draft a PR for cellranger using this orbit commit and run the dev tests and a small sample of single-ended and paired-ended (3-5 total) tests and compare their metrics? Presumably they should be mostly unchanged. If so, 👍

See https://github.com/10XDev/cellranger/pull/3390

Will do!

**Comment by sjackman** [comment]
This PR is superseded by PR https://github.com/10XGenomics/orbit/pull/21.

**Pull request closed without merging**
